### ISSUE TITLE
1.19 is released. Requesting support/port

### ISSUE THREAD

**Issue by mattthw** [gbl/ClickThrough#15]
Just informing you that it is out. Any ETA?

**Comment by gbl** [comment]
I know it is out, I'll probably find time to port it over the weekend. Until then you can try if the 1.19-pre2 version works, as there have been very few changes since then. That version is on https://modrinth.com/mod/clickthrough/version/1.19-pre2-fabric0.53.3-0.4 - please tell me if it works for you!
