### ISSUE TITLE
Chest openning distance is shorter when clicking through an item frame

### ISSUE THREAD

**Issue by MadMoose0** [gbl/ClickThrough#17]
As said in title, you have to be closer to a container to be able to click through an item frame compared to clicking at the edge around it.

**Comment by icynstant** [comment]
Why did you close it? It's still a problem for me

**Comment by gbl** [comment]
Because it's nothing I can control. 
Make the following experiment, with or without clickthrough, doesn't matter:

Have a double chest with an item frame on one side. Stand in front of the chest, far enough so you can't open it, and press F3. Alternate between looking at both sides of the chest.

Now, on the debug screen, you see you're targeting a chest block, but you can't click as you're too far.

Slowly approach the chest. At some point, you'll be close enough to open the chest when looking at the blank side, but still can't click the item frame.

Moving even closer, at some point, the debug screen will show that you're targeting the item frame. As soon as this happens, you can click it to open the chest.

So what happens is, while you're too far, Minecraft won't let you click the chest because the item frame is in front of it, and it won't let you click the frame because it's too far to be clicked as an entity. I'm not getting any clicks from MC in this case, so, nothing to pass through to the chest.

As soon as the item frame becomes clickable, that click gets passed to the chest.

**Comment by icynstant** [comment]
> Because it's nothing I can control. Make the following experiment, with or without clickthrough, doesn't matter:
> 
> Have a double chest with an item frame on one side. Stand in front of the chest, far enough so you can't open it, and press F3. Alternate between looking at both sides of the chest.
> 
> Now, on the debug screen, you see you're targeting a chest block, but you can't click as you're too far.
> 
> Slowly approach the chest. At some point, you'll be close enough to open the chest when looking at the blank side, but still can't click the item frame.
> 
> Moving even closer, at some point, the debug screen will show that you're targeting the item frame. As soon as this happens, you can click it to open the chest.
> 
> So what happens is, while you're too far, Minecraft won't let you click the chest because the item frame is in front of it, and it won't let you click the frame because it's too far to be clicked as an entity. I'm not getting any clicks from MC in this case, so, nothing to pass through to the chest.
> 
> As soon as the item frame becomes clickable, that click gets passed to the chest.

Okay, I understand. But there's a mod, "SwingThrough", it lets you attack a mob even if there's grass. So, like, if mob stands in grass, I will attack only mob and don't even touch grass.
So i wonder may be it's possible to make a mod which gonna avoid frame and focus only on chest like SwingTrough does with grass and mob.
