### ISSUE TITLE
Crash when entering the configuration screen

### ISSUE THREAD

**Issue by dzwdz** [gbl/ClickThrough#2]
https://paste.gg/p/anonymous/41a7850cf40e45b5b375be18676b6ec1

**Comment by gbl** [comment]
That's because you're using ClickThrough 1.16.2 with MC 1.16.1.  A few things with the config screen changed in 1.16.2 

As you have my DurabilityViewer as well, and they're using the same config system, you can probably get away with this if you open the clickthrough jar with a zip file viewer (7zip, winzip, winrar, ...) and delete the GBFabricTools.jar inside it. That should make ClickThrough use the one from DurabilityViewer which will probably work.

**Comment by dzwdz** [comment]
Oh, I thought it was for 1.16.1 too, sorry. Also I can confirm that removing the jar fixes the issue, thanks :)

**Comment by gbl** [comment]
There might be another crash, actually, because the way how to read what's on a sign has changed as well. So the 1.16.2 version might crash on 1.16 when you click a sign. I've uploaded a version for 1.16/1.16.1 right now.
