### ISSUE TITLE
1.19.4 support?

### ISSUE THREAD

**Issue by RandomGgames** [gbl/ClickThrough#25]

**Comment by gbl** [comment]
Come on, opening 3 issues about this when there is already an open issue about 1.20, including discussion, doesn't help. I'm not playing MC any more (actually haven't been playing since 1.16) so updating is quite low on my list especially as Mojang changed so many things, making the updated quite nontrivial.

**Comment by RandomGgames** [comment]
That's understandable. I saw the 1.20 module discussion but wasn't sure exactly what it was. What takes you away from MC?
