### ISSUE TITLE
Items Disappearing

### ISSUE THREAD

**Issue by Valerian9** [gbl/ClickThrough#36]
Sometimes when i rejoin my world after leaving it the items inside the item frame disappear and just get deleted, now im not 100% sure if its this mod because i am also using the Toggle Item Frames mod so it might be because of that one, so im just reporting this problem to both.

**Comment by gbl** [comment]
Very unlikely that this has anything do do with ClickThrough, because my mod doesn't do any persistent changes to the wold. The only thing it does is, if you right click, ask "what was the player looking at", and, if it's a sign or item frame attached to a container, tell the server "the player clicked the container" instead of ".. clicked the sign".  But I don't change the item frames in any way.
